openapi: 3.0.0
info:
  title: Track Shipment
  version: '1.0'
  description: 'An API to fetch the parcel services url using the tracking number to track shipments '
  contact:
    name: Sumbul Chishty
    url: 'http://se.com'
    email: sumbul.chishty@se.com
servers:
  - url: 'https://api.qa.se.com/v1/reference-data/supply-chain/track-shipment'
paths:
  /shipments:
    parameters: []
    post:
      summary: 'track shipments'
      operationId: post-trackshipments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  trackUrl:
                    type: string
                    description: carrier url for shipment tracking
                  code:
                    type: string
                    description: |
                      code for exception or success
              examples:
                shipment track - response:
                  value:
                    trackUrl: 'https://wwwapps.ups.com/tracking/tracking.cgi?tracknum=abcdefgh'
                    code: S
        '400':
          $ref: '#/components/responses/Common_Oas3_400'
        '401':
          $ref: '#/components/responses/Common_Oas3_401'
        '403':
          $ref: '#/components/responses/Common_Oas3_403'
        '404':
          $ref: '#/components/responses/Common_Oas3_404'
        '429':
          $ref: '#/components/responses/Common_Oas3_429'
        '500':
          $ref: '#/components/responses/Common_Oas3_500'
      description: Shipment tracking url by shipment tracking number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                backOfficeId:
                  type: string
                  description: |
                    ERP back office system code
                carrier:
                  type: string
                  description: parcel carrier
                trackingNumber:
                  type: string
                  description: Shipment document tracking number
                partOrderLineBfoId:
                  type: string
                  description: |
                    Front office part order line ID
                shipToCountry:
                  type: string
                  description: |
                    Shipping country code
              required:
                - backOfficeId
                - trackingNumber
            examples:
              trackshipments - Request:
                value:
                  backOfficeId: BBO_EU
                  carrier: UPS
                  trackingNumber: Ship Doc 8939275416
                  partOrderLineBfoId: a1p1H000004BYSHQA4
                  shipToCountry: FR
components:
  schemas:
    ErrorResponse:
      type: object
      title: Error Response - OAS3
      description: Error response returned to the consumer when an HTTP error status has occurred.
      properties:
        code:
          type: string
          example: MISSING_FIELD or 12345
          description: |-
            Service-defined error code which may be numeric or a string.

            Errors detected by the APIM platform result in the following codes.

            BAD_REQUEST (for 400)
            UNAUTHORIZED (for 401)
            FORBIDDEN (for 403)
            NOT_FOUND (for 404)
            GONE (for 410)
            PRECONDITION_FAILED (for 412)
            TOO_MANY_REQUESTS (for 429)
            INTERNAL_SERVER_ERROR (for 500)
            NOT_IMPLEMENTED (for 501)

            Any specific service validation errors would replace BAD_REQUEST.
        userMessage:
          type: string
          example: 'Request is invalid and cannot be processed due one or more issues such as syntax errors, missing required fields, out of range values, conflicting query parameters, or unknown URI.'
          description: Human-readable general description of the error.
        developerMessage:
          type: string
          description: Optional human-readable description of the error details.
          example: 'Required field is missing: productSku'
        moreInfo:
          type: string
          description: 'Optional error details or link to error documentation, which has more information about the error.'
          example: 'https://example.com/product-master/v1/error/12345'
      required:
        - code
        - userMessage
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.qa.se,com/token'
          refreshUrl: ''
          scopes: {}
  responses:
    Common_Oas3_400:
      description: 'Request is invalid and cannot be processed due one or more issues such as syntax errors, missing required fields, out of range values, conflicting query parameters, or unknown URI.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                code: BAD_REQUEST
                userMessage: 'Request is invalid and cannot be processed due one or more issues such as syntax errors, missing required fields, out of range values, conflicting query parameters, or unknown URI.'
                developerMessage: Request content is malformed or exceeded structural limits
                moreInfo: 'https://example.com/error/123'
    Common_Oas3_401:
      description: 'The client is not authorized to perform this request because its identity has not yet been established, or the token is invalid or has expired.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                code: UNAUTHORIZED
                userMessage: 'The client is not authorized to perform this request because its identity has not yet been established, or the token is invalid or has expired.'
                developerMessage: Invalid Access Token
                moreInfo: 'https://example.com/error/123'
    Common_Oas3_403:
      description: The client does not have permission to perform the requested action e.g. POST or DELETE.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                code: FORBIDDEN
                userMessage: The client does not have permission to perform the requested action e.g. POST or DELETE.
                developerMessage: Http verb DELETE is not supported for path suffix /installed-products/track
                moreInfo: 'https://example.com/error/123'
    Common_Oas3_404:
      description: Requested resource does not exist on the server. It is assumed that the URI is valid for this type of resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                code: NOT_FOUND
                userMessage: Requested resource does not exist on the server. It is assumed that the URI is valid for this type of resource.
                developerMessage: Records not found
                moreInfo: 'https://example.com/error/123'
    Common_Oas3_429:
      description: Number of requests has exceeded the client's rate limits.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                code: TOO_MANY_REQUESTS
                userMessage: Number of requests has exceeded the clientâ€™s rate limits.
                developerMessage: Spike arrest violation
                moreInfo: 'https://example.com/error/123'
    Common_Oas3_500:
      description: Requested operation encountered an unexpected server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                code: INTERNAL_SERVER_ERROR
                userMessage: Requested operation encountered an unexpected server error.
                developerMessage: 'Target service is unavailable, please try again later.'
                moreInfo: 'https://example.com/error/123'
security:
  - oauth: []
